name: archimedes
favicon: null
layout_spectrum: 0.05551066203042865
typography_spectrum: 0.740292037371546
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.2664024350233376
  lightness: 0.1782121655996889
  saturation: 0.15267615183256567
  rhythmicContrast: 0.5842813698109239
purpose: []
